### ISSUE TITLE
An AWS deployment would not always have internet

### ISSUE THREAD

**Issue by imesh** [wso2/cloudformation-is#4]
**Description:**
The Identity Server Cloud Formation template seems to have assumed that it will have access to the internet [1], [2] for executing the installation process. In almost all AWS deployments WSO2 servers are installed in a private subnets which would not have internet connectivity. This is done as a security measure for isolating the WSO2 servers from outside networks.

This design principle has been followed in API Manager Cloud Formation template by creating AMIs for each region using a Packer script which would execute the first phase of the WSO2 product installation at the AMI creation time. Identity Server Cloud Formation template may need to follow the same pattern.

**Affected Product Version:**
5.3.0, 5.4.0

[1] https://github.com/wso2/cloudformation-is/blob/master/scripts/wso2-is-with-alb-cf-template.yml#L373
[2] https://github.com/wso2/cloudformation-is/blob/master/scripts/setup-env.sh#L16

**Comment by VimukthiPerera** [comment]
This flow is currently followed in https://github.com/wso2/aws-is and the issue can be closed.
